### ISSUE TITLE
Uncaught Error: Cannot read property 'showItemInFolder' of undefinedTypeError: Cannot read prope...

### ISSUE THREAD

**Issue by jianbingfang** [alefragnani/useful-context-menu#5]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.2.4
**System**: Microsoft Windows 10 Enterprise
**Thrown From**: [useful-context-menu](https://github.com/alefragnani/useful-context-menu) package, v0.3.0

### Stack Trace

Uncaught Error: Cannot read property 'showItemInFolder' of undefined
TypeError: Cannot read property 'showItemInFolder' of undefined
    at EventEmitter.<anonymous> (C:\Users\jifang\AppData\Local\atom\app-1.2.4\resources\atom.asar\browser\lib\rpc-server.js:224:37)
    at emitMany (events.js:108:13)
    at EventEmitter.emit (events.js:182:7)
    at EventEmitter.<anonymous> (C:\Users\jifang\AppData\Local\atom\app-1.2.4\resources\atom.asar\browser\api\lib\web-contents.js:97:23)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)

```
At C:\Users\jifang\AppData\Local\atom\app-1.2.4\resources\atom.asar\renderer\api\lib\remote.js:105

Error: Cannot read property 'showItemInFolder' of undefined
TypeError: Cannot read property 'showItemInFolder' of undefined
    at EventEmitter.<anonymous> (C:\Users\jifang\AppData\Local\atom\app-1.2.4\resources\atom.asar\browser\lib\rpc-server.js:224:37)
    at emitMany (events.js:108:13)
    at EventEmitter.emit (events.js:182:7)
    at EventEmitter.<anonymous> (C:\Users\jifang\AppData\Local\atom\app-1.2.4\resources\atom.asar\browser\api\lib\web-contents.js:97:23)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
    at metaToValue (C:\Users\jifang\AppData\Local\atom\app-1.2.4\resources\atom.asar\renderer\api\lib\remote.js:105:15)
    at Object.RemoteMemberFunction [as showItemInFolder] (C:\Users\jifang\AppData\Local\atom\app-1.2.4\resources\atom.asar\renderer\api\lib\remote.js:139:26)
    at Object.module.exports.UsefulContextMenu.openInFileManager (file:///C:/Users/jifang/.atom/packages/useful-context-menu/lib/useful-context-menu.coffee:61:11)
    at atom-workspace.subscriptions.add.atom.commands.add.useful-context-menu:open-in-file-manager (file:///C:/Users/jifang/.atom/packages/useful-context-menu/lib/useful-context-menu.coffee:30:108)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\jifang\AppData\Local\atom\app-1.2.4\resources\app.asar\src\command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (C:\Users\jifang\AppData\Local\atom\app-1.2.4\resources\app.asar\src\command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\jifang\AppData\Local\atom\app-1.2.4\resources\app.asar\src\command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (C:\Users\jifang\AppData\Local\atom\app-1.2.4\resources\app.asar\src\atom-environment.js:993:28)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
    at EventEmitter.ipc.sendSync (C:\Users\jifang\AppData\Local\atom\app-1.2.4\resources\atom.asar\renderer\api\lib\ipc.js:21:31)
    at BrowserWindow.RemoteMemberFunction [as emit] (C:\Users\jifang\AppData\Local\atom\app-1.2.4\resources\atom.asar\renderer\api\lib\remote.js:138:29)
    at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (C:\Users\jifang\AppData\Local\atom\app-1.2.4\resources\app.asar\src\context-menu-manager.js:156:33)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentContextmenu (C:\Users\jifang\AppData\Local\atom\app-1.2.4\resources\app.asar\src\window-event-handler.js:252:47)
    at HTMLDocument.<anonymous> (C:\Users\jifang\AppData\Local\atom\app-1.2.4\resources\app.asar\src\window-event-handler.js:3:61)
```

### Commands

```
     -9:41.2.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -9:38.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -8:04.2.0 atom-terminal-panel:toggle-autocompletion (atom-text-editor.editor.is-focused)
     -8:04.1.0 core:select-all (atom-text-editor.editor.is-focused)
     -7:59.9.0 atom-terminal-panel:toggle-autocompletion (atom-text-editor.editor.is-focused)
     -7:59.9.0 core:select-all (atom-text-editor.editor.is-focused)
     -7:48.3.0 atom-terminal-panel:toggle-autocompletion (atom-text-editor.editor.is-focused)
     -7:48.2.0 core:select-all (atom-text-editor.editor.is-focused)
     -7:46.3.0 atom-terminal-panel:toggle-autocompletion (atom-text-editor.editor.is-focused)
     -7:46.3.0 core:select-all (atom-text-editor.editor.is-focused)
     -7:42.9.0 atom-terminal-panel:toggle-autocompletion (atom-text-editor.editor.is-focused)
     -7:42.8.0 core:select-all (atom-text-editor.editor.is-focused)
     -4:02.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -2:30.1.0 useful-context-menu:open-in-file-manager (atom-text-editor.editor.power-mode.is-focused)
     -2:24.4.0 useful-context-menu:open-in-terminal (atom-text-editor.editor.power-mode.is-focused)
  2x -0:14.4.0 useful-context-menu:open-in-file-manager (atom-text-editor.editor.power-mode.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
activate-power-mode, v0.3.2
atom-beautify, v0.28.19
atom-terminal-panel, v4.4.4
autocomplete-paths, v1.0.2
emmet, v2.3.16
file-icons, v1.6.13
javascript-snippets, v1.0.0
minimap, v4.16.2
new-tab, v0.4.1
pigments, v0.19.1
script, v3.2.0
useful-context-menu, v0.3.0

# Dev
No dev packages
```

**Comment by alefragnani** [comment]
Hi, sorry for the delay. 

Are you still experiencing this issue? I used most of the Atom released versions and never saw this problem. I'm using 1.3.1 and 1.4.0 beta, with no problems too.
